# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "mshannaq/odoo12_ubuntu18.04_accounting_pdfreports"
  config.vm.box_version = "0.0.1"
  config.vm.network "public_network"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  end
end
