workflows:
  build-vagrant-box:
    name: Build Vagrant Box
    instance_type: mac_mini_m1
    scripts:
      - name: Install VirtualBox
        script: brew install --cask virtualbox@beta
      - name: Install Vagrant
        script: |
          brew tap hashicorp/tap
          brew install hashicorp/tap/hashicorp-vagrant
      - name: Build Vagrant Box
        script: |
          vagrant up
          vagrant package --output box/windows-11-enterprise-evaluation-10.0.26100.Build.26100-virtual-box.box --vagrantfile Vagrantfile
